#!/usr/bin/env php

<?php

require getcwd().'/vendor/autoload.php';

use IBroStudio\ModuleHelper\Cli\Cli;
use IBroStudio\ModuleHelper\Cli\Registry;

(new Cli(new Registry(), ...Cli::parseArgv($argv)))->build();

