#!/usr/bin/env php

<?php

require getcwd().'/vendor/autoload.php';

use function Laravel\Prompts\select;
use function Laravel\Prompts\text;
use function Laravel\Prompts\form;
use function Laravel\Prompts\info;
use function Laravel\Prompts\alert;
use function Laravel\Prompts\note;
use function Laravel\Prompts\warning;

alert('Package installed successfully.');
note('Package installed successfully.');
info('Package installed successfully.');
warning('Package installed successfully.');

$responses = form()
    ->text('What is your name?', required: true)
    ->password('What is your password?', validate: function ($value) {
        echo $value; die();
    })
    ->confirm('Do you accept the terms?')
    ->submit();

var_dump($argv);

$domain = select(
    'Domain',
    ['Api'],
);

//$name = text('What is your name?');